initial commit
shoma0987/bootcamp pull request #1
Opened 2020-12-14 14:04 UTC by shoma0987

1日目、本日の進捗を報告いたします。

2020-12-14 14:11 UTC, shoma0987 commented on log/202012/20201214.txt
> +-初のbootcamp、githubそのもの使い方の各種commandの種類、gitignore役割、そしてalias登録など改めて学び、理解を確認できる良い機会となった。所々、ググるのに苦労しました。
追加コメント:github-flowに則り、developをbranchとして作成して以後管理を行う。

2020-12-14 14:16 UTC, shoma0987 commented on log/202012/20201214.txt
> +実績時間:
実績時間:5時間(ググル内容が多く、想定より時間を費やしてしまった)

2020-12-15 01:37 UTC, masashi-hasegawa requested changes
- 追加コメントは全てファイルに記載してください。
修正しましょう。
- 次回からでよいですが、ブランチ名を工夫しましょう。
github-flowをもう一度しらべましょう。
developという命名は適切ではありません。
作業内容に即した命名にしましょう。
- logの書き方は良いですね。
今後もご自身で工夫していきましょう。

2020-12-15 01:37 UTC, masashi-hasegawa commented on log/202012/20201214.txt
> +実績時間:
コメントではなく、ファイルに記載しましょう。

2020-12-15 01:37 UTC, masashi-hasegawa commented on log/202012/20201214.txt
> +-よく使いそうなgit commandを.gitconfigのaliasに登録して、以後時間削減できるようにした(ex;st,co,br)。
エイリアスへの登録良いですね。

2020-12-15 01:37 UTC, masashi-hasegawa commented on log/202012/20201214.txt
> +READ.mdを作成し、remoteにpushしたのですが、現時点で中に何かを記載する必要がありますでしょうか。
- READ.mdではなくREADME.mdですよ。
もう一度調べてみましょう。
- masterを直接触らないでください。
masterブランチにpushは一番してはいけないことですよ。
次回より必ずブランチを切り、プルリクエストを出してくださいね。

2020-12-15 09:37 UTC, closed without merging