test_for_array__instance_method
shoma0987/bootcamp pull request #28
Opened 2020-12-22 11:30 UTC by shoma0987

Arrayクラスのインスタンスメソッドを複数調べ、利用例をコードしました(Ruby)

2020-12-23 01:44 UTC, masashi-hasegawa requested changes
- コメントを参考に修正しましょう。
- 公式ドキュメントをみて他のメソッドも調べてみましょう。

2020-12-23 01:44 UTC, masashi-hasegawa commented on ruby/test_for_array_method.rb
> +array1 = ["orange","grape","apple"]
array1 = ["orange", "grape", "apple"]

 space1つですが、すごく重要です。
以下をもう一度みてみましょう。
https://github.com/rubocop-hq/ruby-style-guide

2020-12-23 01:44 UTC, masashi-hasegawa commented on ruby/test_for_array_method.rb
> +puts array6.find(){|item| item=="beer"} #(nilを返す)
array6.find { |item| item == "beer" }

引数のないメソッドは他のメソッドと同様に()を省略しましょう。

2020-12-23 11:12 UTC, shoma0987 commented on ruby/test_for_array_method.rb
> +array1 = ["orange","grape","apple"]
ありがとうございます。spaceについて、best practiceを確認し修正しました。
また、公式ドキュメントの中で理解しておくべき便利なメソッドも追加しました。

2020-12-24 04:06 UTC, masashi-hasegawa approved these changes

2020-12-24 08:03 UTC, merged